"use strict";

/* Deliberately canvas-first: one active page, rAF drawing and debounced compact data saves. */
(function (global) {
  let root, canvas, ctx, subject, user, notebook, activePage = 0, tool = "gel", color = "#4d4260", width = 3;
  let drawing = null, redo = [], saveTimer = 0, frame = 0, mounted = false, zoom = 1, pan = { x: 0, y: 0 }, saveVersion = 0;
  const pointers = new Map(), images = new Map();
  const key = () => `itera:notebook:${user?.id || "guest"}:${subject?.id || "subject"}`;
  const templates = { lined: "Liniat", grid: "Pătrățele", blank: "Simplu" };
  const fresh = () => ({ version: 3, pages: [{ template: "lined", background: "#fffdf9", strokes: [], elements: [] }], updatedAt: Date.now() });
  const page = () => notebook.pages[activePage];

  function load() { try { const saved = JSON.parse(localStorage.getItem(key()) || "null"); return saved?.pages?.length ? saved : fresh(); } catch (_) { return fresh(); } }
  async function loadCloud() { const { data, error } = await supabaseClient.from("notebooks").select("content,updated_at").eq("user_id", user.id).eq("subject_id", subject.id).maybeSingle(); if (error || !data?.content?.pages?.length || !mounted) return; if (Number(data.content.updatedAt || 0) > Number(notebook.updatedAt || 0)) { notebook = data.content; notebook.pages.forEach(item => { item.strokes ||= []; item.elements ||= []; item.background ||= "#fffdf9"; }); localStorage.setItem(key(), JSON.stringify(notebook)); render(); } updateStatus("Sincronizat"); }
  function saveSoon() { clearTimeout(saveTimer); updateStatus("Se salvează…"); saveTimer = global.setTimeout(() => { void persist(); }, 700); }
  async function persist() { if (!notebook || !user || !subject) return; const version = ++saveVersion; notebook.updatedAt = Date.now(); const snapshot = JSON.parse(JSON.stringify(notebook)); try { localStorage.setItem(key(), JSON.stringify(snapshot)); } catch (_) { updateStatus("Spațiul local este plin"); return; } const { error } = await supabaseClient.from("notebooks").upsert({ user_id: user.id, subject_id: subject.id, content: snapshot, updated_at: new Date().toISOString() }, { onConflict: "user_id,subject_id" }); if (mounted && version === saveVersion) updateStatus(error ? "Salvat local — sincronizarea va fi reluată" : "Salvat și sincronizat"); }
  function updateStatus(text) { root?.querySelector("[data-notebook-status]")?.replaceChildren(text); }

  async function mount(subjectId) {
    root = document.getElementById("notebookViewRoot"); if (!root) return; mounted = true;
    root.innerHTML = '<div class="subjects-spa-state">Se deschide caietul…</div>';
    const { data: { session } } = await supabaseClient.auth.getSession(); user = session?.user;
    if (!user || !mounted) return;
    const { data } = await supabaseClient.from("subjects").select("id,name,color").eq("id", subjectId).eq("user_id", user.id).maybeSingle();
    if (!data || !mounted) { root.innerHTML = '<div class="subjects-spa-state">Caietul nu a fost găsit.</div>'; return; }
    subject = data; notebook = load(); notebook.pages.forEach(item => { item.strokes ||= []; item.elements ||= []; item.background ||= "#fffdf9"; }); activePage = 0; redo = []; zoom = 1; pan = { x: 0, y: 0 }; render(); void loadCloud();
  }
  function unmount() { clearTimeout(saveTimer); if (notebook) { try { localStorage.setItem(key(), JSON.stringify(notebook)); } catch (_) {} void persist(); } mounted = false; root = canvas = ctx = drawing = null; pointers.clear(); }
  function desk() { return '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M12 18h24v10H12zM16 28l-3 12m19-12 3 12M12 40h8m8 0h8M19 13h10" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>'; }

  function render() {
    const current = page();
    root.innerHTML = `<a class="subjects-spa-back" href="#/subjects/${subject.id}">← ${escape(subject.name)}</a><section class="notebook-shell" style="--subject:${subject.color || "#f3a9c5"}">
      <header class="notebook-head"><div class="notebook-title-icon">${desk()}</div><div><p class="eyebrow">Caietul tău</p><h2>${escape(subject.name)}</h2></div><small data-notebook-status>Pregătit</small></header>
      <div class="notebook-toolbar" role="toolbar" aria-label="Instrumente caiet"><button data-tool="gel" class="active">Gel</button><button data-tool="ballpoint">Pix</button><button data-tool="pencil">Creion</button><button data-tool="highlighter">Marker</button><button data-tool="eraser">⌫</button><button data-tool="text">T</button><button data-add-image>▧</button><button data-undo>↶</button><button data-redo>↷</button><button data-zoom-out>−</button><span class="notebook-zoom" data-zoom>100%</span><button data-zoom-in>+</button><input data-color type="color" value="${color}" aria-label="Culoare"><input data-width type="range" min="1" max="12" value="${width}" aria-label="Grosime"><select data-template aria-label="Tip pagină">${Object.entries(templates).map(([id, label]) => `<option value="${id}" ${current.template === id ? "selected" : ""}>${label}</option>`).join("")}</select><select data-background aria-label="Culoarea paginii"><option value="#fffdf9">Ivory</option><option value="#ffffff">Alb</option><option value="#f6f2ff">Lavandă</option><option value="#eef7f5">Mentă</option><option value="#fff4e8">Piersică</option></select><input data-image-input type="file" accept="image/*" hidden></div>
      <p class="notebook-gesture-hint">Apple Pencil scrie; un deget deplasează pagina, două degete fac zoom.</p><div class="notebook-paper-wrap"><canvas class="notebook-paper" aria-label="Caiet pentru scris cu Apple Pencil"></canvas></div>
      <footer class="notebook-footer"><button data-prev ${activePage === 0 ? "disabled" : ""}>‹ Pagina anterioară</button><span>Pagina ${activePage + 1} din ${notebook.pages.length}</span><button data-next ${activePage === notebook.pages.length - 1 ? "disabled" : ""}>Pagina următoare ›</button><button class="primary-small-button" data-add-page>+ Pagină</button></footer></section>`;
    canvas = root.querySelector("canvas"); ctx = canvas.getContext("2d", { desynchronized: true }); resize(); bind();
  }
  function resize() { if (!canvas) return; const ratio = Math.min(global.devicePixelRatio || 1, 2), w = canvas.clientWidth, h = canvas.clientHeight; canvas.width = Math.max(1, Math.round(w * ratio)); canvas.height = Math.max(1, Math.round(h * ratio)); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); redraw(); }
  function paintPaper() { const w = canvas.clientWidth, h = canvas.clientHeight; ctx.clearRect(0, 0, w, h); ctx.fillStyle = page().background || "#fffdf9"; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = "rgba(142,169,207,.28)"; ctx.lineWidth = 1; if (page().template === "lined") for (let y = 42; y < h; y += 28) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } if (page().template === "grid") { for (let x = 20; x < w; x += 20) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); } for (let y = 20; y < h; y += 20) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } } ctx.strokeStyle = "rgba(224,109,136,.26)"; ctx.beginPath(); ctx.moveTo(44, 0); ctx.lineTo(44, h); ctx.stroke(); }
  function drawStroke(stroke) { if (!stroke.points?.length) return; const w = canvas.clientWidth, h = canvas.clientHeight, points = stroke.points; ctx.save(); ctx.globalAlpha = stroke.tool === "highlighter" ? .24 : stroke.tool === "pencil" ? .72 : 1; ctx.strokeStyle = stroke.color; ctx.lineCap = ctx.lineJoin = "round"; for (let i = 1; i < points.length; i++) { const a = points[i - 1], b = points[i], next = points[i + 1]; ctx.lineWidth = stroke.width * ((Number(a[2]) || 1) + (Number(b[2]) || 1)) / 2; ctx.beginPath(); ctx.moveTo(a[0] * w, a[1] * h); if (next) ctx.quadraticCurveTo(b[0] * w, b[1] * h, (b[0] + next[0]) * w / 2, (b[1] + next[1]) * h / 2); else ctx.lineTo(b[0] * w, b[1] * h); ctx.stroke(); } ctx.restore(); }
  function drawElement(element) { const w = canvas.clientWidth, h = canvas.clientHeight; if (element.type === "text") { ctx.save(); ctx.fillStyle = element.color || color; ctx.font = `${element.size || 21}px Manrope, sans-serif`; ctx.fillText(element.text, element.x * w, element.y * h); ctx.restore(); return; } if (element.type === "shape") { ctx.save(); ctx.strokeStyle = element.color; ctx.lineWidth = element.width; ctx.lineCap = ctx.lineJoin = "round"; const x = element.x * w, y = element.y * h, sw = element.w * w, sh = element.h * h; ctx.beginPath(); if (element.shape === "line") { ctx.moveTo(x, y); ctx.lineTo(x + sw, y + sh); } else if (element.shape === "arrow") { ctx.moveTo(x, y); ctx.lineTo(x + sw, y + sh); ctx.lineTo(x + sw - Math.sign(sw || 1) * 14, y + sh - Math.sign(sh || 1) * 7); ctx.moveTo(x + sw, y + sh); ctx.lineTo(x + sw - Math.sign(sw || 1) * 7, y + sh - Math.sign(sh || 1) * 14); } else if (element.shape === "triangle") { ctx.moveTo(x + sw / 2, y); ctx.lineTo(x + sw, y + sh); ctx.lineTo(x, y + sh); ctx.closePath(); } else if (element.shape === "rectangle") ctx.rect(x, y, sw, sh); else ctx.ellipse(x + sw / 2, y + sh / 2, Math.abs(sw / 2), Math.abs(sh / 2), 0, 0, Math.PI * 2); ctx.stroke(); ctx.restore(); return; } if (element.type === "image") { let image = images.get(element.src); if (!image) { image = new Image(); image.onload = queueRedraw; image.src = element.src; images.set(element.src, image); } if (image.complete) ctx.drawImage(image, element.x * w, element.y * h, element.w * w, element.h * h); } }
  function redraw() { if (!ctx || !canvas) return; paintPaper(); page().strokes.forEach(drawStroke); page().elements.forEach(drawElement); }
  function queueRedraw() { if (frame) return; frame = requestAnimationFrame(() => { frame = 0; redraw(); }); }
  function setZoom(next) { zoom = Math.max(1, Math.min(3.2, next)); canvas.style.transform = `translate(${pan.x}px,${pan.y}px) scale(${zoom})`; root.querySelector("[data-zoom]").textContent = `${Math.round(zoom * 100)}%`; }
  function point(event) { const rect = canvas.getBoundingClientRect(); const pressure = event.pointerType === "pen" && Number.isFinite(event.pressure) && event.pressure > 0 ? Math.max(.35, Math.min(1.8, event.pressure * 1.5)) : 1; return [Number(((event.clientX - rect.left) / rect.width).toFixed(4)), Number(((event.clientY - rect.top) / rect.height).toFixed(4)), pressure]; }
  function begin(event) { if (event.pointerType === "mouse" && event.button !== 0) return; event.preventDefault(); canvas.setPointerCapture(event.pointerId); pointers.set(event.pointerId, { x: event.clientX, y: event.clientY }); const writing = event.pointerType === "pen" || event.pointerType === "mouse"; if (pointers.size === 2) { if (drawing) page().strokes.pop(); drawing = null; const [a,b] = [...pointers.values()]; canvas.dataset.gestureDistance = String(Math.hypot(a.x-b.x,a.y-b.y)); canvas.dataset.gestureZoom = String(zoom); canvas.dataset.gestureCenter = `${(a.x+b.x)/2},${(a.y+b.y)/2}`; canvas.dataset.gesturePan = `${pan.x},${pan.y}`; return; } canvas.dataset.gesturePan = `${pan.x},${pan.y}`; canvas.dataset.gestureCenter = `${event.clientX},${event.clientY}`; if (!writing) return; if (tool === "text") return addText(event); if (tool === "eraser") return eraseAt(point(event)); redo = []; drawing = { tool, color, width: tool === "highlighter" ? width * 3 : width, points: [point(event)] }; page().strokes.push(drawing); queueRedraw(); }
  function move(event) { if (!pointers.has(event.pointerId)) return; event.preventDefault(); pointers.set(event.pointerId, { x: event.clientX, y: event.clientY }); if (pointers.size >= 2) { const [a,b] = [...pointers.values()], distance = Math.hypot(a.x-b.x,a.y-b.y), base = Number(canvas.dataset.gestureDistance || distance), [centerX,centerY] = String(canvas.dataset.gestureCenter || "0,0").split(",").map(Number), [panX,panY] = String(canvas.dataset.gesturePan || "0,0").split(",").map(Number); pan = { x: panX + ((a.x+b.x)/2-centerX), y: panY + ((a.y+b.y)/2-centerY) }; setZoom(Number(canvas.dataset.gestureZoom || zoom) * distance / base); return; } if (event.pointerType === "touch") { const [startX,startY] = String(canvas.dataset.gestureCenter || "0,0").split(",").map(Number), [panX,panY] = String(canvas.dataset.gesturePan || "0,0").split(",").map(Number); pan = { x: panX + event.clientX - startX, y: panY + event.clientY - startY }; setZoom(zoom); return; } if (tool === "eraser") return eraseAt(point(event)); if (!drawing || !canvas.hasPointerCapture(event.pointerId)) return; const next = point(event), last = drawing.points.at(-1); if (Math.abs(next[0]-last[0])+Math.abs(next[1]-last[1]) < .0015) return; drawing.points.push(next); queueRedraw(); }
  function recognizeShape(stroke) { const points = stroke.points || []; if (points.length < 2 || points.length > 36) return null; const xs = points.map(p => p[0]), ys = points.map(p => p[1]), minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys), w = maxX - minX, h = maxY - minY; if (Math.max(w, h) < .08) return null; const first = points[0], last = points.at(-1), closed = Math.hypot(first[0] - last[0], first[1] - last[1]) < .045, closeTo = (x,y) => points.some(p => Math.hypot(p[0]-x,p[1]-y) < .035); if (closed) { const rectangle = closeTo(minX,minY) && closeTo(maxX,minY) && closeTo(maxX,maxY) && closeTo(minX,maxY), triangle = closeTo((minX+maxX)/2,minY) && closeTo(minX,maxY) && closeTo(maxX,maxY); return { type:"shape", shape: rectangle ? "rectangle" : triangle ? "triangle" : "ellipse", x:minX, y:minY, w, h, color:stroke.color, width:stroke.width }; } const tipIndex = points.reduce((best, point, index) => Math.hypot(point[0]-first[0],point[1]-first[1]) > Math.hypot(points[best][0]-first[0],points[best][1]-first[1]) ? index : best, 0), tip = points[tipIndex]; if (points.length >= 6 && tipIndex > 0 && tipIndex < points.length - 2) return { type:"shape", shape:"arrow", x:first[0], y:first[1], w:tip[0]-first[0], h:tip[1]-first[1], color:stroke.color, width:stroke.width }; const dx = last[0] - first[0], dy = last[1] - first[1], length = Math.hypot(dx, dy); const deviation = points.reduce((sum, p) => sum + Math.abs(dy * p[0] - dx * p[1] + last[0] * first[1] - last[1] * first[0]) / length, 0) / points.length; if (deviation < .012) return { type:"shape", shape: "line", x:first[0], y:first[1], w:dx, h:dy, color:stroke.color, width:stroke.width }; return null; }
  function finish(event) { pointers.delete(event.pointerId); if (!drawing) return; if (drawing.points.length === 1) drawing.points.push([drawing.points[0][0]+.001,drawing.points[0][1]+.001, drawing.points[0][2] || 1]); const shape = recognizeShape(drawing); if (shape) { page().strokes.pop(); page().elements.push(shape); } drawing = null; redraw(); saveSoon(); }
  function eraseAt(at) { const radius = Math.max(.012, width / Math.max(canvas.clientWidth, canvas.clientHeight) * 3); const removed = page().strokes.filter(stroke => stroke.points.some(p => Math.hypot(p[0]-at[0], p[1]-at[1]) < radius)); if (!removed.length) return; page().strokes = page().strokes.filter(stroke => !removed.includes(stroke)); redo.push(...removed); queueRedraw(); saveSoon(); }
  function addText(event) { const at = point(event), input = document.createElement("input"); input.className = "notebook-text-editor"; input.placeholder = "Scrie aici"; input.style.left = `${event.clientX}px`; input.style.top = `${event.clientY}px`; document.body.append(input); input.focus(); const commit = () => { const text = input.value.trim(); input.remove(); if (text) { page().elements.push({ type:"text", text, x:at[0], y:at[1], color, size:Math.max(16, width * 5) }); saveSoon(); redraw(); } }; input.addEventListener("keydown", e => { if (e.key === "Enter") commit(); if (e.key === "Escape") input.remove(); }); input.addEventListener("blur", commit, { once:true }); }
  async function addImage(file) { if (!file) return; updateStatus("Pregătesc poza…"); const source = await fileToDataUrl(file); const image = await loadImage(source); const max = 1600, ratio = Math.min(1, max / Math.max(image.width, image.height)); const off = document.createElement("canvas"); off.width = Math.max(1, Math.round(image.width * ratio)); off.height = Math.max(1, Math.round(image.height * ratio)); off.getContext("2d").drawImage(image,0,0,off.width,off.height); const src = off.toDataURL("image/jpeg", .8); const aspect = off.height / off.width; page().elements.push({ type:"image", src, x:.12, y:.14, w:.76, h:Math.min(.7,.76 * aspect) }); saveSoon(); redraw(); }
  function fileToDataUrl(file) { return new Promise((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
  function loadImage(src) { return new Promise((resolve,reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = src; }); }
  function bind() { root.querySelectorAll("[data-tool]").forEach(button => button.addEventListener("click", () => { tool = button.dataset.tool; root.querySelectorAll("[data-tool]").forEach(item => item.classList.toggle("active", item === button)); })); root.querySelector("[data-color]").addEventListener("input", e => color = e.target.value); root.querySelector("[data-width]").addEventListener("input", e => width = Number(e.target.value)); root.querySelector("[data-template]").addEventListener("change", e => { page().template = e.target.value; saveSoon(); redraw(); }); root.querySelector("[data-background]").value = page().background || "#fffdf9"; root.querySelector("[data-background]").addEventListener("change", e => { page().background = e.target.value; saveSoon(); redraw(); }); root.querySelector("[data-undo]").addEventListener("click", () => { const item = page().strokes.pop() || page().elements.pop(); if (item) { redo.push(item); saveSoon(); redraw(); } }); root.querySelector("[data-redo]").addEventListener("click", () => { const item = redo.pop(); if (item) { (item.type ? page().elements : page().strokes).push(item); saveSoon(); redraw(); } }); root.querySelector("[data-zoom-in]").addEventListener("click", () => setZoom(zoom+.2)); root.querySelector("[data-zoom-out]").addEventListener("click", () => setZoom(zoom-.2)); root.querySelector("[data-add-image]").addEventListener("click", () => root.querySelector("[data-image-input]").click()); root.querySelector("[data-image-input]").addEventListener("change", e => { void addImage(e.target.files?.[0]); e.target.value = ""; }); root.querySelector("[data-prev]").addEventListener("click", () => { activePage--; zoom=1;pan={x:0,y:0};render(); }); root.querySelector("[data-next]").addEventListener("click", () => { activePage++; zoom=1;pan={x:0,y:0};render(); }); root.querySelector("[data-add-page]").addEventListener("click", () => { notebook.pages.push({template:page().template,background:page().background || "#fffdf9",strokes:[],elements:[]}); activePage=notebook.pages.length-1; zoom=1;pan={x:0,y:0};saveSoon();render(); }); canvas.addEventListener("pointerdown",begin,{passive:false}); canvas.addEventListener("pointermove",move,{passive:false}); canvas.addEventListener("pointerup",finish); canvas.addEventListener("pointercancel",finish); global.addEventListener("resize",resize,{once:true}); }
  function escape(value) { return String(value || "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"); }
  global.IteraNotebookView = Object.freeze({ mount, unmount });
})(window);
